{% set version = "0.2.13" %}

package:
  name: sccache
  version: {{ version }}

source:
  url: https://github.com/mozilla/sccache/archive/{{ version }}.tar.gz
  sha256: 81c973cf9a89e77f02a6b5710298531ba2e50d2555e8a931e505fbf570522e2a

build:
  number: 1
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
  host:
    - openssl

test:
  commands:
    - sccache --version
    - sccache --help
    - conda inspect linkages -p $PREFIX sccache  # [not win]
    - conda inspect objects -p $PREFIX sccache  # [osx]

about:
  home: https://github.com/mozilla/sccache
  summary: sccache is ccache with cloud storage
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  description: |
    Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids
    compilation when possible, storing a cache in a remote storage using the
    Amazon Simple Cloud Storage Service (S3) API, the Google Cloud Storage (GCS) API,
    or Redis.
  doc_url: https://github.com/mozilla/sccache
  dev_url: https://github.com/mozilla/sccache

extra:
  recipe-maintainers:
    - luizirber
