{% set version = "0.8.1" %}

package:
  name: sccache
  version: {{ version }}

source:
  url: https://github.com/mozilla/sccache/archive/v{{ version }}.tar.gz
  sha256: 30b951b49246d5ca7d614e5712215cb5f39509d6f899641f511fb19036b5c4e5

build:
  number: 1
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - rust
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - openssl  #[linux]

test:
  commands:
    - sccache --version
    - sccache --help

about:
  home: https://github.com/mozilla/sccache
  summary: sccache is ccache with cloud storage
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  license_family: APACHE
  description: |
    Sccache is a ccache-like tool. It is used as a compiler wrapper and avoids
    compilation when possible, storing a cache in a remote storage using the
    Amazon Simple Cloud Storage Service (S3) API, the Google Cloud Storage (GCS) API,
    or Redis.
  doc_url: https://github.com/mozilla/sccache
  dev_url: https://github.com/mozilla/sccache

extra:
  recipe-maintainers:
    - luizirber
    - wolfv
    - jonashaag
    - baszalmstra
