conda_forge_output_validation: true
linux_aarch64:
  enabled: true
provider:
  linux_aarch64: default
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
